################
#VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/xebra/gun/verbose 0

#################
#SEED
/run/random/setRandomSeed 0

##################
# isotropic emission
/xebra/gun/angtype iso

# make sure the volume below is a bit larger than the object the source will be confined to
/xebra/gun/type   Volume  
/xebra/gun/shape  Cylinder
# include entire TPC
#/xebra/gun/center 0. 0. 0. cm
#/xebra/gun/radius 0.1 m
#/xebra/gun/halfz  0.25 m

# confine more:
# /xebra/gun/center 0. 0. 133. mm
# /xebra/gun/radius 20. mm
# /xebra/gun/halfz  10. mm

##################
# Select the volume to confine the source. E.g. /xebra/gun/confine LXe*
## /xebra/gun/confine test*
# /xebra/gun/confine LXe*
# /xebra/gun/confine GXe*
## /xebra/gun/confine LXe_weir*
## /xebra/gun/confine GXe_weir*
## /xebra/gun/confine LXe_extra_filling*
# /xebra/gun/confine TPC_SS_PMTfixture*
# /xebra/gun/confine TPC_Al_filler*
# /xebra/gun/confine TPC_Cu_FSE*
# /xebra/gun/confine TPC_PTFE_pillar*
# /xebra/gun/confine TPC_SS_BottomRing*
# /xebra/gun/confine TPC_SS_TopRing*
# /xebra/gun/confine TPC_SS_pillar*
# /xebra/gun/confine TPC_PTFE_filler*
# /xebra/gun/confine TPC_PTFE_BottomPMTHolder*
# /xebra/gun/confine TPC_PTFE_spacer*
# /xebra/gun/confine TPC_PTFE_reflector*
# /xebra/gun/confine TPC_SS_gate_ring*
# /xebra/gun/confine TPC_PTFE_TopPMTHolder*
# /xebra/gun/confine TPC_SS_cathode*
# /xebra/gun/confine TPC_SS_anode*
# /xebra/gun/confine TPC_SS_TopMesh*
# /xebra/gun/confine TPC_PEEK_weir*
# /xebra/gun/confine TPC_Torlon_rod*
# /xebra/gun/confine PMT0_Ceramic_Stem*
# /xebra/gun/confine PMT0_Photocathode*
# /xebra/gun/confine PMT0_Window*
# /xebra/gun/confine PMT0_Inner_Vacuum*
# /xebra/gun/confine PMT0_Body
# /xebra/gun/confine PMT0*
/xebra/gun/confine PMT1*
# /xebra/gun/confine PMT1_Body
# /xebra/gun/confine PMT1_Window
# /xebra/gun/confine PMT1_Ring

##################
#/xebra/gun/energytype Spectrum
#/xebra/gun/energyspectrum ./macros/spectra/neutron/flat.dat
#/xebra/gun/particle gamma 
/xebra/gun/particle geantino

##################
# MC acceleration techniques for gammas. AP playground: if false it is not used
/run/forced/setVarianceReduction false

#
# Scintillation processes in the LXe
#
#/Xe/detector/setLXeScintillation false

# Tree Filling options
/run/writeEmpty true


